- name: Ensure mariadb server and mysql python client are installed
  apt: pkg={{ item }} 
  with_items:
    - python-mysqldb
    - mariadb-server

- name: Ensure mysql binds to internal interface
  template: >
    src=etc/99-openstack.cnf 
    dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf 
    owner=root 
    group=root 
    mode=0644
  notify: restart mariadb


# Set root password
# UPDATE mysql.user SET Password=PASSWORD('mysecret') WHERE User='root';
# FLUSH PRIVILEGES;

- name: update mysql root password for all root accounts
  mysql_user: >
    name=root
    host=localhost
    password={{ root_db_password }}

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: copy .my.cnf file with root password credentials
  template: >
    src=root/.my.cnf
    dest=/root/.my.cnf
    owner=root
    mode=0600


- name: update mysql root password for all root accounts
  mysql_user: >
    name=root
    host={{ item }}
    password={{ root_db_password }}
  with_items:
    - "{{ controller_ip }}"
    - localhost
    - 127.0.0.1

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - "{{ controller_ip }}"
    - "{{ inventory_hostname_short }}"
    - 127.0.0.1
    - ::1






















# http://dev.mysql.com/doc/refman/5.6/en/default-privileges.html


# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user


