apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: letschat
  name: letschat-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: letschat
  template:
    metadata:
      labels:
        name: letschat
    spec:
      containers:
      - image: sdelements/lets-chat
        name: letschat
        ports:
        - containerPort: 3000
          name: http-server

